version: 2
jobs:
  build:
    working_directory: ~/funkwhale-cli
    docker:
      - image: tomaka/rust-mingw-docker:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Windows stuff
          command: 'rustup target add x86_64-pc-windows-gnu'
      - run:
          name: Build Windows x86_64 binary
          command: 'cargo rustc --release --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc'
      - run:
          name: Build Linux x86_64 binary
          command: 'cargo build --target x86_64-unknown-linux-gnu --release'
      - save_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
            - "~/.cargo"
      - run:
          name: Chmod Linux binary
          command: 'chmod +x ~/funkwhale-cli/target/x86_64-unknown-linux-gnu/release/funkwhale-cli'
      - run:
          name: Move binaries
          command: |
            mkdir binaries
            mv ~/funkwhale-cli/target/x86_64-unknown-linux-gnu/release/funkwhale-cli binaries/funkwhale-cli-linux-x86_64
            mv ~/funkwhale-cli/target/x86_64-pc-windows-gnu/release/funkwhale-cli.exe binaries/funkwhale-cli.exe
      - store_artifacts:
          path: ~/funkwhale-cli/binaries
      - persist_to_workspace:
          root: ~/funkwhale-cli
          paths:
            - binaries/funkwhale-cli-linux-x86_64
            - binaries/funkwhale-cli.exe
  make_pre_release:
    docker:
      - image: golang:1.12.4-stretch
    steps:
      - attach_workspace:
          at: ~/funkwhale-cli
      - run:
          name: Install ghr
          command: "go get -u github.com/tcnksm/ghr"
      - run:
          name: "Publish pre-release on Github"
          command: |
            VERSION=$(~/funkwhale-cli/binaries/funkwhale-cli-linux-x86_64 --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -prerelease -delete $(echo ${VERSION} | awk '{print $2}') ~/funkwhale-cli/binaries

workflows:
  version: 2
  build:
    jobs:
      - build
      - make_pre_release:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
