version: 2
jobs:
  build:
    working_directory: ~/funkwhale-cli
    docker:
      - image: tomaka/rust-mingw-docker:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Windows stuff
          command: 'rustup target add x86_64-pc-windows-gnu'
      - run:
          name: Build Windows x86_64 binary
          command: 'cargo rustc --release --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc'
      - run:
          name: Build Linux x86_64 binary
          command: 'cargo build --target x86_64-unknown-linux-gnu --release'
      - save_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
            - "~/.cargo"
      - store_artifacts:
          path: ~/funkwhale-cli/target/x86_64-unknown-linux-gnu/release/funkwhale-cli
      - store_artifacts:
          path: ~/funkwhale-cli/target/x86_64-pc-windows-gnu/release/funkwhale-cli.exe

workflows:
  version: 2
  build:
    jobs:
      - build
