version: 2
jobs:
  build:
    working_directory: ~/funkwhale-cli
    docker:
      - image: rust:1.34
    steps:
      - checkout
      - run:
          name: Install Windows stuff
          command: 'rustup target add x86_64-pc-windows-msvc'
      - run:
          name: Build Windows x86_64 binary
          command: 'cargo build --target x86_64-pc-windows-gnu --release'
      - run:
          name: Build Linux x86_64 binary
          command: 'cargo build --target x86_64-unknown-linux-gnu --release'
      - store_artifacts:
          path: ~/funkwhale-cli/target/x86_64-unknown-linux-gnu/release/funkwhale-cli
          destination: x86_64-unknown-linux-gnu
      - store_artifacts:
          path: ~/funkwhale-cli/target/x86_64-pc-windows-gnu/release/funkwhale-cli
          destination: x86_64-pc-windows-gnu

workflows:
  version: 2
  build:
    jobs:
      - build
